version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bookshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookshop
      MYSQL_USER: bookshop
      MYSQL_PASSWORD: bookshoppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bookshop-backend/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - bookshop-network

  # Spring Boot Backend
  backend:
    build:
      context: ./bookshop-backend
      dockerfile: Dockerfile
    container_name: bookshop-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookshop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: bookshop
      SPRING_DATASOURCE_PASSWORD: bookshoppass
      BOOKSHOP_APP_JWT_SECRET: bookshopSecretKey2024SuperSecureLongKeyForJWTTokenGenerationAndValidationPurposes
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - bookshop-network
    volumes:
      - ./bookshop-backend/uploads:/app/uploads

  # React Frontend
  frontend:
    build:
      context: ./bookshop-frontend
      dockerfile: Dockerfile
    container_name: bookshop-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bookshop-network

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: bookshop-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - bookshop-network
    profiles:
      - production

volumes:
  mysql_data:

networks:
  bookshop-network:
    driver: bridge
